In [ ]:
import keras

In [ ]:
from keras.preprocessing.text import one_hot

sent=['the glass of milk', 'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [ ]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [ ]:
voc_size=10000

In [ ]:
one_hot_repr=[one_hot(word,voc_size) for word in sent]

In [ ]:
print(one_hot_repr)

[[4157, 981, 9546, 7496], [4157, 981, 9546, 1318], [4157, 1217, 9546, 2982], [9306, 6306, 7181, 4642, 5748], [9306, 6306, 7181, 4642, 9646], [7160, 4157, 4309, 9546, 9235], [2151, 3283, 8498, 4642]]


In [ ]:
from keras.preprocessing.sequence import pad_sequences
from keras.layers import Embedding
from keras.models import Sequential

In [ ]:
import numpy as np

In [ ]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=8)
print(embedded_docs)

[[   0    0    0    0 4157  981 9546 7496]
 [   0    0    0    0 4157  981 9546 1318]
 [   0    0    0    0 4157 1217 9546 2982]
 [   0    0    0 9306 6306 7181 4642 5748]
 [   0    0    0 9306 6306 7181 4642 9646]
 [   0    0    0 7160 4157 4309 9546 9235]
 [   0    0    0    0 2151 3283 8498 4642]]


In [ ]:
dim=10
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [ ]:
print(model.predict(embedded_docs))

[[[ 0.03607097  0.01047133  0.04560694  0.03857211 -0.01541995
   -0.02185361 -0.01824254 -0.03429531  0.00753146  0.02365139]
  [ 0.03607097  0.01047133  0.04560694  0.03857211 -0.01541995
   -0.02185361 -0.01824254 -0.03429531  0.00753146  0.02365139]
  [ 0.03607097  0.01047133  0.04560694  0.03857211 -0.01541995
   -0.02185361 -0.01824254 -0.03429531  0.00753146  0.02365139]
  [ 0.03607097  0.01047133  0.04560694  0.03857211 -0.01541995
   -0.02185361 -0.01824254 -0.03429531  0.00753146  0.02365139]
  [ 0.0370809  -0.01676259  0.0389743   0.04074445 -0.0293888
   -0.04492098  0.04415736  0.03663487  0.02701534  0.03018581]
  [-0.03924035  0.04724411 -0.00287491 -0.02003037  0.0448045
    0.01194907  0.01449528 -0.04876057 -0.02524345 -0.02239564]
  [-0.0025604   0.02091995  0.02267588  0.03316149 -0.03521781
    0.01715032 -0.01483004 -0.014994   -0.00440209  0.00270308]
  [-0.03282233  0.03833947 -0.03767446  0.01450939  0.00296204
   -0.02122845 -0.04176086  0.02554596 -0.01996336

In [ ]:
print(model.predict(embedded_docs)[0])

[[ 0.03607097  0.01047133  0.04560694  0.03857211 -0.01541995 -0.02185361
  -0.01824254 -0.03429531  0.00753146  0.02365139]
 [ 0.03607097  0.01047133  0.04560694  0.03857211 -0.01541995 -0.02185361
  -0.01824254 -0.03429531  0.00753146  0.02365139]
 [ 0.03607097  0.01047133  0.04560694  0.03857211 -0.01541995 -0.02185361
  -0.01824254 -0.03429531  0.00753146  0.02365139]
 [ 0.03607097  0.01047133  0.04560694  0.03857211 -0.01541995 -0.02185361
  -0.01824254 -0.03429531  0.00753146  0.02365139]
 [ 0.0370809  -0.01676259  0.0389743   0.04074445 -0.0293888  -0.04492098
   0.04415736  0.03663487  0.02701534  0.03018581]
 [-0.03924035  0.04724411 -0.00287491 -0.02003037  0.0448045   0.01194907
   0.01449528 -0.04876057 -0.02524345 -0.02239564]
 [-0.0025604   0.02091995  0.02267588  0.03316149 -0.03521781  0.01715032
  -0.01483004 -0.014994   -0.00440209  0.00270308]
 [-0.03282233  0.03833947 -0.03767446  0.01450939  0.00296204 -0.02122845
  -0.04176086  0.02554596 -0.01996336 -0.02093198]]